"""card catalog: split Card into CardType + instance

Revision ID: 382488dd0106
Revises: 68ab078c6a05
Create Date: 2026-08-04 12:29:32.296984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '382488dd0106'
down_revision: Union[str, None] = '68ab078c6a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('rarity', postgresql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'HOLO_RARE', 'ULTRA_RARE', 'CHASE', name='card_rarity', create_type=False), nullable=True),
    sa.Column('set', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_type_sku'), 'card_type', ['sku'], unique=True)
    op.add_column('card', sa.Column('card_type_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_card_card_type_id'), 'card', ['card_type_id'], unique=False)
    op.create_foreign_key(None, 'card', 'card_type', ['card_type_id'], ['id'])
    op.drop_column('card', 'image_url')
    op.drop_column('card', 'number')
    op.drop_column('card', 'rarity')
    op.drop_column('card', 'set')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('set', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('card', sa.Column('rarity', postgresql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'HOLO_RARE', 'ULTRA_RARE', 'CHASE', name='card_rarity'), autoincrement=False, nullable=False))
    op.add_column('card', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('card', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_index(op.f('ix_card_card_type_id'), table_name='card')
    op.drop_column('card', 'card_type_id')
    op.drop_index(op.f('ix_card_type_sku'), table_name='card_type')
    op.drop_table('card_type')
    # ### end Alembic commands ###
