"""booster catalog: ClosedBooster fields, OpenedBooster link, card order

Revision ID: 68ab078c6a05
Revises: d4e6f8a0b2c3
Create Date: 2026-08-04 04:02:46.196907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68ab078c6a05'
down_revision: Union[str, None] = 'd4e6f8a0b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_booster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_front_url', sa.String(), nullable=True),
    sa.Column('image_back_url', sa.String(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closed_booster_sku'), 'closed_booster', ['sku'], unique=True)
    op.drop_table('closed_booster_stock')
    op.add_column('card', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('opened_booster', sa.Column('closed_booster_id', sa.UUID(), nullable=True))
    op.alter_column('opened_booster', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('opened_booster', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('opened_booster', 'video_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('opened_booster', 'filmed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_opened_booster_closed_booster_id'), 'opened_booster', ['closed_booster_id'], unique=False)
    op.create_foreign_key(None, 'opened_booster', 'closed_booster', ['closed_booster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opened_booster', type_='foreignkey')
    op.drop_index(op.f('ix_opened_booster_closed_booster_id'), table_name='opened_booster')
    op.alter_column('opened_booster', 'filmed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('opened_booster', 'video_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('opened_booster', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('opened_booster', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('opened_booster', 'closed_booster_id')
    op.drop_column('card', 'position')
    op.create_table('closed_booster_stock',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('in_stock', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('closed_booster_stock_pkey')),
    sa.UniqueConstraint('sku', name=op.f('closed_booster_stock_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_closed_booster_sku'), table_name='closed_booster')
    op.drop_table('closed_booster')
    # ### end Alembic commands ###
