services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: claw_media 
    restart: unless-stopped
    # ports:
    #   - '1935:1935'
    #   - '8554:8554'
    #   - '8888:8888'
    #   - '8889:8889'
    #   - '8890:8890/udp'
    #   - '8189:8189/udp'
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    # networks:
    #   - claw_network
    network_mode: "host"
    
  proxy:
    container_name: claw_proxy
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - next
      - fastapi
      - db
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - claw_certbot_etc:/etc/letsencrypt
      - claw_certbot_www:/var/www/certbot
    networks:
      - claw_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  next:
    container_name: claw_next
    build: ./next
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    env_file: .env
    networks:
      - claw_network

  db:
    image: postgres:latest
    container_name: claw_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - claw_postgres_data:/var/lib/postgresql/data
    networks:
      - claw_network
    env_file: .env

  fastapi:
    container_name: claw_fastapi
    build: ./fastapi
    expose:
      - '5000'
    env_file: .env
    networks:
      - claw_network

volumes:
  claw_postgres_data:
  claw_certbot_etc:
    external: true
  claw_certbot_www:
    external: true

networks:
  claw_network:
    name: claw_network
    driver: bridge
