services:
  socket:
    build: ./server
    devices:
      - /dev/gpiomem:/dev/gpiomem
    expose:
      - '5000'
    network_mode: "host"
    restart: always
    
  ffmpeg:
    build: ./ffmpeg
    devices:
      - '/dev/video0:/dev/video0'
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command: http localhost:5000 --url=peluchera.ngrok.app --config /etc/ngrok/ngrok.yml
    env_file: ./.env
    network_mode: "host"
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok/ngrok.yml
