services:
  socket:
    build: ./server
    devices:
      - /dev/gpiomem:/dev/gpiomem
    expose:
      - '5000'
    
  # ffmpeg:
  #   build: ./ffmpeg
  #   devices:
  #     - '/dev/video0:/dev/video0'
  #   restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command: http socket:5000 --url=peluchera.ngrok.app
    env_file: ./.env