services:
  flask:
    build: ./server
    ports:
      - '80:5000'
    
  ffmpeg:
    build: ./ffmpeg
    devices:
      - '/dev/video0:/dev/video0'
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command: http 80 --url=peluchera.ngrok.app
    env_file: ./.env